# Generated by Django 5.2.8 on 2025-12-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0002_alter_cart_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('PD', 'Paid'), ('SH', 'Shipped'), ('CN', 'Cancelled')], default='PN', max_length=2)),
                ('date_placed', models.DateTimeField(auto_now=True)),
                ('source_cart_session_key', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('contact_email', models.EmailField(max_length=254)),
                ('shipping_address_line1', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_zip', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date_placed'],
            },
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-quantity']},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout_api.order')),
            ],
        ),
    ]
