# Generated by Django 5.2.8 on 2026-01-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0004_cart_created_at_cart_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('COM', 'Completed')], default='ACT', max_length=3),
        ),
    ]
