# Generated by Django 5.2.8 on 2026-01-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0005_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('PRO', 'Processing'), ('COM', 'Completed')], default='ACT', max_length=3),
        ),
    ]
