# Generated by Django 5.2.8 on 2026-01-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0008_cartitem_unique_cart_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price']},
        ),
    ]
