# Generated by Django 5.2.8 on 2026-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0009_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('SUC', 'Succeeded'), ('FAI', 'Failed')], default='PEN', max_length=3)),
                ('order_id', models.CharField(max_length=100)),
                ('payment_intent_id', models.CharField(max_length=50, unique=True)),
                ('payment_method_id', models.CharField(max_length=50)),
            ],
        ),
    ]
