# Generated by Django 5.2.8 on 2026-02-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0011_alter_paymentintent_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='payment_method_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
