# Generated by Django 5.2.8 on 2026-04-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0016_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-item_id']},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
    ]
