# Generated by Django 5.2.8 on 2026-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0017_alter_orderitem_options_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
