# Generated by Django 5.2.8 on 2026-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0018_alter_orderitem_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
