# Generated by Django 5.2.8 on 2026-04-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0019_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='Test', max_length=20),
            preserve_default=False,
        ),
    ]
