# Generated by Django 5.2.8 on 2026-04-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0020_orderitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
