# Generated by Django 5.2.8 on 2026-06-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0021_alter_orderitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('item_id', 'order'), name='unique_order_item'),
        ),
    ]
