# Generated by Django 5.2.8 on 2026-06-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0022_alter_orderitem_item_id_orderitem_unique_order_item'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='orderitem',
            name='unique_order_item',
            constraint=models.UniqueConstraint(fields=('item_id', 'order'), name='unique_order_item', violation_error_message='The same item cannot be added twice in a cart'),
        ),
    ]
