# Generated by Django 5.2.8 on 2026-06-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_api', '0023_alter_orderitem_unique_order_item'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='orderitem',
            name='unique_order_item',
            constraint=models.UniqueConstraint(fields=('item_id', 'order'), name='unique_order_item'),
        ),
    ]
